services:
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    container_name: mysql
    restart: always
    environment:    
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    volumes:
      - .docker/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 30s
      retries: 5

  rabbitmq:
    image: rabbitmq:latest
    platform: linux/amd64
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 20s
      retries: 5

  migration:
    build:
      context: .
      dockerfile: Dockerfile.migration
    container_name: migration
    depends_on:
      - mysql
    environment:
      DB_URL: "mysql://root:root@tcp(mysql:3306)/orders"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      migration:
        condition: service_started
    env_file:
      - ./cmd/ordersystem/.env
    ports:
      - "8000:8000"      # Porta para o servidor web
      - "50051:50051"    # Porta para o servidor gRPC
      - "8080:8080"      # Porta para o servidor GraphQL