version: '3.8'

services:
  mysql:
    image: mysql/mysql-server:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    volumes:
      - .docker/mysql:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - localNetwork

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - localNetwork

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: migrate
    depends_on:
      - mysql
      - rabbitmq
    entrypoint: >
      /bin/sh -c "
        until mysql -h mysql -u root -proot -e 'select 1'; do
          echo 'Aguardando MySQL...';
          sleep 3;
        done;
        echo 'Iniciando migrate...';
        migrate -path=/migrations -database 'mysql://root:root@tcp(mysql:3306)/orders' -verbose up;        
      "
    volumes:
      - ./cmd/ordersystem:/app
      - ./sql/migrations:/migrations
    networks:
      - localNetwork

networks:
  localNetwork:
    driver: bridge    