GET http://localhost:8000/orders HTTP/1.1
Host: localhost:8000
Content-Type: application/json




# Resposta:
# HTTP/1.1 200 OK
# Date: Sun, 10 Nov 2024 01:34:01 GMT
# Content-Length: 272
# Content-Type: text/plain; charset=utf-8
# Connection: close

# {
#   "Quantity": 4,
#   "Orders": [
#     {
#       "ID": "Teste 1",
#       "Price": 100.5,
#       "Tax": 0.5,
#       "FinalPrice": 101
#     },
#     {
#       "ID": "Teste evans",
#       "Price": 100.6,
#       "Tax": 0.5,
#       "FinalPrice": 101.1
#     },
#     {
#       "ID": "Teste Graphl",
#       "Price": 110.2,
#       "Tax": 2,
#       "FinalPrice": 112.2
#     },
#     {
#       "ID": "Teste Graphl 2",
#       "Price": 110.2,
#       "Tax": 2,
#       "FinalPrice": 112.2
#     }
#   ]
# }
